# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QR499DeEx1OtgS2Dl3N3TLK8yjUFu0gu
"""

import requests
from bs4 import BeautifulSoup
import time
import os

TOKEN = os.getenv("TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

URL = "https://www.cbhours.com/user/victoria_and_michael.html"

estado_anterior = None

def enviar_mensaje(texto):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    requests.post(url, data={"chat_id": CHAT_ID, "text": texto})

def obtener_estado():
    headers = {"User-Agent": "Mozilla/5.0"}
    r = requests.get(URL, headers=headers)
    soup = BeautifulSoup(r.text, "html.parser")

    texto = soup.text.lower()

    if "online" in texto:
        return "online"
    return "offline"

while True:
    estado = obtener_estado()

    if estado == "online" and estado_anterior != "online":
        enviar_mensaje("🔥 ESTÁN ONLINE 🔥")

    estado_anterior = estado
    time.sleep(180)